# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: microservice-vote
  tag: latest
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  type: ClusterIP
  servicePort: 9080
  servicePortHttps: 9443
ingress:
  enabled: true
  rewriteTarget: "/vote"
  path: "/vote"
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100
istio:
  enabled: false
  weight: 100
test: false


## Cloudant parameters
ibm-cloudant-dev:
  ## image parameters
  image:
    repository: ibmcom/cloudant-developer
    tag: latest
    pullPolicy: Always
  initImage:
    repository: "ibmcom/icp-initcontainer"
    tag: "1.0.0"

  ## global persistence parameters
  persistence:
    enabled: false
    useDynamicProvisioning: false

  databasePVC:
    name: "cloudant-pvc"
    ## specify the storageClassName you want to use
    ## if you don't specify a storageClassName it will use the default
    storageClassName: ""
    ## Specify the name of the Existing Claim to be used by your application
    ## empty string means don't use an existClaim
    existingClaimName: ""
    size: 3Gi

  ## database parameters
  database:
    readinessProbePeriodSeconds: 2
    readinessProbeInitialDelaySeconds: 30
    livenessProbePeriodSeconds: 2
    livenessProbeInitialDelaySeconds: 200